import Head from "next/head";
import Image from "next/image";
import { Box, Button, Container, Heading, Textarea } from "@chakra-ui/react";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Heading mt={8}>AIレシピツクールヨ</Heading>
        <Image
          src="/vercel.svg"
          alt="Vercel Logo"
          width={100}
          height={24}
          priority
        />
        <form>
          <Box mt={8}>
            <Textarea
              name="foods"
              rows={8}
              placeholder={`なす
ぴーまん`}
              required
            />
          </Box>
          <Box mt={4}>
            <Button type="submit" colorScheme="blue">
              AIにレシピを作ってもらう
            </Button>
          </Box>
        </form>
      </Container>
    </>
  );
}
